version: '3.8'

services:
  origin:
    build:
      context: ./docker/origin
      dockerfile: Dockerfile
    ports:
      - 8080:80
    restart: always

  imgproxy:
    image: darthsim/imgproxy:v3.4.0
    ports:
      - 8081:8080
    restart: always
    environment:
      - IMGPROXY_MAX_SRC_RESOLUTION=18.0
      - IMGPROXY_LOG_LEVEL=warn

  thumbor:
    build:
      context: ./docker/thumbor
      dockerfile: Dockerfile
    ports:
      - 8082:8888
    restart: always

  weserv-images:
    build:
      context: ./docker/weserv-images
      dockerfile: Dockerfile
    ports:
      - 8083:80
    restart: always

  picfit:
    build:
      context: ./docker/picfit/
      dockerfile: Dockerfile
    ports:
      - 8084:3001
    restart: always
    environment:
      - PICFIT_CONFIG_PATH=/config.json

  imageproxy:
    image: ghcr.io/willnorris/imageproxy:v0.11.2
    ports:
      - 8085:8080
    restart: always
    environment:
      - IMAGEPROXY_SCALEUP=true

